name: Desplegar Frontend en Firebase Hosting

on:
  push:
    branches:
      - main
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar, Compilar y Desplegar
        run: |
          cd frontend-gimnasio
          npm ci
          npm run build
          npx firebase-tools deploy --only hosting --token "${{ secrets.FIREBASE_TOKEN }}"
